#!/bin/bash
appRoot="/data/evl/anishi2/cs523/pix2pix-tensorflow"
dirRoot="/data/evl/anishi2/cs523/CS523Project3/server.js"

# cleanup previous image
rm -rf $dirRoot/public/output/*

# Test
python3 $appRoot/pix2pix.py \
		  --mode test \
		  --output_dir $dirRoot/public/output \
		  --input_dir $dirRoot/public/images \
		  --checkpoint $appRoot/edges2pkm_train-Lyra30

rm -rf $dirRoot/public/images
mkdir $dirRoot/public/images
sleep 5
