#!/bin/bash
appRoot="/data/evl/anishi2/cs523/pix2pix-tensorflow"

python3 $appRoot/pix2pixCluster.py \
		  --mode train \
		  --output_dir $appRoot/facades_train \
		  --max_epochs 10 \
		  --input_dir $appRoot/facades/train \
		  --which_direction BtoA \
		  --job_name ps \
		  --task_index $idx &
		  
idx=-1
# ignore 1
for i in {1, 34}
do
	node=`printf lyra-%02d $i`
	#idx=`expr $i - 1`

	if [ "$idx" -ge 0 ]
	then
		echo "================= $node: client $idx ================="
		#UDD="$HOME/.config/chrome-nfs/$node"
		#mkdir -p $UDD
		#UDD="/scratch/evl/evldemo/chrome/$node"
		ssh -fx $node python3 $appRoot/pix2pixCluster.py \
		  --mode train \
		  --output_dir $appRoot/facades_train \
		  --max_epochs 10 \
		  --input_dir $appRoot/facades/train \
		  --which_direction BtoA \
		  --job_name worker \
		  --task_index $idx
	fi
	#param="$global_param --user-data-dir=$UDD"
	
	#ssh -fx $node "env DISPLAY=:0.0 google-chrome $param --app=http://$server/session.html\?page=display.html\?clientID=$idx\&hash=$hash" &
	let "idx = idx + 1"
done

# python3 /data/evl/anishi2/cs523/pix2pix-tensorflow/pix2pixCluster.py --mode train --output_dir /data/evl/anishi2/cs523/pix2pix-tensorflow/facades_train --max_epochs 10 --input_dir /data/evl/anishi2/cs523/pix2pix-tensorflow/facades/train --which_direction BtoA --job_name ps --task_index 0

# python3 /data/evl/anishi2/cs523/pix2pix-tensorflow/pix2pixCluster.py --mode train --output_dir /data/evl/anishi2/cs523/pix2pix-tensorflow/facades_train --max_epochs 10 --input_dir /data/evl/anishi2/cs523/pix2pix-tensorflow/facades/train --which_direction BtoA --job_name worker --task_index 0